is3d: true
find_lr: false
checkpoints:
  continue_training: false
  test_mode: false
  ckpt_path: '/home/say26747/best.ckpt'
  log_pictures: false
  save_nifty: true

dataset:
  name: "LA_heart_loader"
  crop_size: [96,96,96]
  path_to_data: "/home/say26747/Desktop/datasets/Left Atrial"

datatype: 'LA'

check_val_every_n_epoch: 10

data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 12
    pin_memory: true
    persistent_workers: true
  validation: 
    batch_size: 1
    shuffle: false
    num_workers: 12
    pin_memory: true
    persistent_workers: true
  test:
    batch_size: 1
    shuffle: false
    num_workers: 12
    pin_memory: false
    persistent_workers: true

training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay : 0.00003
      nesterov: true
  criterion:
    params: 
      dice_weight: 1.0
      bce_weight: 1.0
  scheduler:
    name: 'CustomDecayLR'
    params:
      max_epochs: 250
  epochs: 250
  
model: 
  name: 'lhUNET_SGD_LA_TEST_V9'
  params: # the class arguments defined above
    spatial_shapes: [96, 96, 96]
    do_ds: false # Deep Supervision
    in_channels: 1
    out_channels: 2
        
      # encoder params
    cnn_kernel_sizes: [3,3]
    cnn_features: [12,16]
    cnn_strides: [2,2]
    cnn_maxpools: [true, true]
    cnn_dropouts: 0.0
    cnn_blocks: nn # n: resunet, d: deformconv, b: basicunet
    hyb_kernel_sizes: [3,3,3]
    hyb_features: [32,64,128]
    hyb_strides: [2,2,2]
    hyb_maxpools: [true,true,true]
    hyb_cnn_dropouts: 0.0
    hyb_tf_proj_sizes: [64,32,0]
    hyb_tf_repeats: [1,1,1]
    hyb_tf_num_heads: [4,4,8]
    hyb_tf_dropouts: 0.0
    hyb_cnn_blocks: nnn # n: resunet, d: deformconv, b: basicunet
    hyb_vit_blocks: SSC # s: dlka_special_v2, S: dlka_sp_seq, c: dlka_channel_v2, C: dlka_ch_seq
    # hyb_vit_sandwich: false
    hyb_skip_mode: "cat" # "sum" or "cat"
    hyb_arch_mode: "residual" # sequential, residual, parallel, collective
    hyb_res_mode: "sum" # "sum" or "cat"
                
    # decoder params
    dec_hyb_tcv_kernel_sizes: [5,5,5]
    dec_cnn_tcv_kernel_sizes: [5,5]
    dec_cnn_blocks: null
    dec_tcv_bias: false
    dec_hyb_tcv_bias: false
    dec_hyb_kernel_sizes: null
    dec_hyb_features: null
    dec_hyb_cnn_dropouts: null
    dec_hyb_tf_proj_sizes: null
    dec_hyb_tf_repeats: null
    dec_hyb_tf_num_heads: null
    dec_hyb_tf_dropouts: null
    dec_cnn_kernel_sizes: null
    dec_cnn_features: null
    dec_cnn_dropouts: null
    dec_hyb_cnn_blocks: null
    dec_hyb_vit_blocks: null
    # dec_hyb_vit_sandwich: null
    dec_hyb_skip_mode: null
    dec_hyb_arch_mode: "collective" # sequential, residual, parallel, collective, sequential-lite
    dec_hyb_res_mode: null

use_sliding_window: true
sliding_window_params:
  overlap: 0.85
  mode: 'gaussian'